### ISSUE TITLE
Add ultralytics classification model

### ISSUE THREAD

**Issue by dnth** [dnth/x.infer#25]

**Comment by dnth** [comment]
Feel free to make a pull request. Let me know if you need any help

**Comment by 315386775** [comment]
@dnth https://github.com/dnth/x.infer/pull/44 this pull request. please check. By the way, I think the other models (seg. pose) of the ultralytics are also very useful, and the rendered result images should be saved. I am writing this part of the code.

**Comment by dnth** [comment]
That will be awesome to have. Many thanks!

**Comment by dnth** [comment]
PR merged - https://github.com/dnth/x.infer/pull/44
